name: TopManager
options:
  bundleIdPrefix: com.topmanager
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    DEVELOPMENT_TEAM: ""

targets:
  TopManager:
    type: application
    platform: macOS
    sources:
      - path: TopManager
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.topmanager.app
        INFOPLIST_FILE: TopManager/Info.plist
        CODE_SIGN_ENTITLEMENTS: TopManager/TopManager.entitlements
        PRODUCT_NAME: TopManager
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: TopManager/Info.plist
    entitlements:
      path: TopManager/TopManager.entitlements
